// lib/data.ts
import { Car, Feature, NavItem } from "@/types";

export const navItems: NavItem[] = [
	{ label: "Home", href: "/" },
	{ label: "Services", href: "/services" },
	{ label: "About", href: "/about" },
];

export const featuredCars: Car[] = [
	{
		id: 1,
		name: "2024 Mpower",
		brand: "BMW",
		make: "BMW",
		model: "911",
		price: "₦45M",
		priceNumeric: 45000000,
		image: "/images/bmw/bm1.jpg",
		year: 2024,
		mileage: 1200,
		transmission: "Automatic",
		fuel: "Premium",
		fuelType: "Petrol",
		bodyType: "Sports Car",
		condition: "Brand New",
		featured: true,
		description:
			"The iconic 911 delivers legendary performance and timeless design.",
		features: [
			"Leather Interior",
			"Sport Chrono Package",
			"Premium Sound System",
		],
		color: "Black",
		engineSize: "3.0L Twin-Turbo",
		drivetrain: "RWD",
	},
	{
		id: 2,
		name: "2023 BMW M4",
		brand: "BMW",
		make: "BMW",
		model: "M4",
		price: "₦89.5M",
		priceNumeric: 89500000,
		image: "/images/Mask_25.webp",
		year: 2023,
		mileage: 8500,
		transmission: "Manual",
		fuel: "Premium",
		fuelType: "Petrol",
		bodyType: "Coupe",
		condition: "Foreign Used",
		featured: true,
		description:
			"Pure driving excitement with precision handling and raw power.",
		features: ["Carbon Fiber Roof", "M Sport Exhaust", "Adaptive Suspension"],
		color: "Blue",
		engineSize: "3.0L I6 Twin-Turbo",
		drivetrain: "RWD",
	},
	{
		id: 3,
		name: "2024 Mercedes AMG GT",
		brand: "Mercedes",
		make: "Mercedes-Benz",
		model: "AMG GT",
		price: "₦145M",
		priceNumeric: 145000000,
		image: "/images/Mask_21.webp",
		year: 2024,
		mileage: 2100,
		transmission: "Automatic",
		fuel: "Premium",
		fuelType: "Petrol",
		bodyType: "Sports Car",
		condition: "Brand New",
		featured: true,
		description: "Combining luxury and performance in a stunning package.",
		features: ["AMG Performance Exhaust", "Burmester Sound", "Dynamic Select"],
		color: "Silver",
		engineSize: "4.0L V8 Twin-Turbo",
		drivetrain: "RWD",
	},
];

export const features: Feature[] = [
	{
		icon: "🏆",
		title: "Premium Selection",
		description: "Handpicked luxury and performance vehicles from top brands",
	},
	{
		icon: "✓",
		title: "Certified Quality",
		description:
			"Every vehicle undergoes rigorous inspection and certification",
	},
	{
		icon: "💰",
		title: "Best Pricing",
		description: "Competitive prices and flexible financing options available",
	},
	{
		icon: "🛡️",
		title: "Warranty Coverage",
		description: "Comprehensive warranty plans for peace of mind",
	},
];

// All cars inventory (for inventory page)
export const allCars: Car[] = [
	...featuredCars,
	{
		id: 4,
		make: "Toyota",
		model: "Camry",
		name: "Toyota Camry",
		brand: "Toyota",
		year: 2022,
		price: "₦18.5M",
		priceNumeric: 18500000,
		mileage: 25000,
		transmission: "Automatic",
		fuelType: "Petrol",
		fuel: "Petrol",
		bodyType: "Sedan",
		condition: "Foreign Used",
		image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
		featured: false,
		description:
			"Well-maintained Toyota Camry in excellent condition. Features include leather seats, sunroof, and advanced safety systems. Perfect for both city driving and long distance travel.",
		color: "Silver",
		engineSize: "2.5L",
		drivetrain: "FWD",
		features: ["Leather Seats", "Sunroof", "Backup Camera", "Cruise Control"],
	},
	{
		id: 5,
		make: "Mercedes-Benz",
		model: "GLE 450",
		name: "Mercedes-Benz GLE 450",
		brand: "Mercedes-Benz",
		year: 2021,
		price: "₦45M",
		priceNumeric: 45000000,
		mileage: 18000,
		transmission: "Automatic",
		fuelType: "Petrol",
		fuel: "Petrol",
		bodyType: "SUV",
		condition: "Foreign Used",
		image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
		featured: false,
		description:
			"Luxury SUV with premium features including panoramic sunroof, premium sound system, and advanced driver assistance. Low mileage and impeccably maintained.",
		color: "Black",
		engineSize: "3.0L V6",
		drivetrain: "4MATIC AWD",
		features: [
			"Panoramic Sunroof",
			"Premium Sound System",
			"360 Camera",
			"Heated Seats",
		],
	},
	{
		id: 6,
		make: "Honda",
		model: "Accord",
		name: "Honda Accord",
		brand: "Honda",
		year: 2023,
		price: "₦22M",
		priceNumeric: 22000000,
		mileage: 5000,
		transmission: "Automatic",
		fuelType: "Hybrid",
		fuel: "Hybrid",
		bodyType: "Sedan",
		condition: "Brand New",
		image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800",
		featured: false,
		description:
			"Brand new Honda Accord Hybrid with exceptional fuel efficiency. Equipped with Honda Sensing safety suite, adaptive cruise control, and premium interior finishes.",
		color: "White Pearl",
		engineSize: "2.0L Hybrid",
		drivetrain: "FWD",
		features: [
			"Honda Sensing",
			"Adaptive Cruise Control",
			"Lane Keep Assist",
			"Apple CarPlay",
		],
	},
];
